name: wizzsales
description: Wizz Sales App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=2.18.1 <3.16.5'

dependencies:
  flutter:
    sdk: flutter
  country_codes: ^2.2.0
  animate_do: ^3.3.4
  audioplayers: ^6.0.0
  pdf: ^3.10.8
  internet_connection_checker: ^1.0.0+1
  group_radio_button: ^1.1.0
  google_maps_flutter: ^2.6.0
  flutter_phoenix: ^1.1.1
  badges: ^3.1.2
  progress_stepper: ^1.0.0
  cached_network_image: ^3.3.1
  chewie: ^1.7.4
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.20
  file_picker: ^6.2.0
  firebase_in_app_messaging: ^0.7.4+8
  flutter_barcode_scanner: ^2.0.0
  fast_contacts: ^1.0.0
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  geocoding: ^2.0.0
  geolocator: ^10.1.0
  intl: any
  path: any
  external_path: ^1.0.3
  path_provider: ^2.1.2
  open_file: ^3.3.2
  syncfusion_flutter_calendar: any
  syncfusion_flutter_signaturepad: ^24.2.8
  syncfusion_flutter_datagrid: ^24.2.7
  syncfusion_flutter_pdfviewer: ^24.1.47
  syncfusion_flutter_sliders: any
  syncfusion_flutter_datagrid_export: ^24.2.5
  syncfusion_flutter_charts: ^24.1.47+2
  syncfusion_flutter_xlsio: ^24.2.5
  permission_handler: ^11.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.3
  video_player: ^2.8.2
  qr_code_scanner: ^1.0.1
  pretty_dio_logger: ^1.3.1
  flutter_local_notifications: ^15.1.1
  dio: ^5.4.0
  mask_text_input_formatter: ^2.8.0
  masked_text_field: ^1.0.2
  intl_phone_field: ^3.2.0
  flutter_sms: ^2.3.3
  awesome_snackbar_content: ^0.1.3
  retrofit: ^4.0.1
  easy_localization: ^3.0.3
  image_picker: ^1.0.0
  mobx:
  flutter_mobx:
  mobx_codegen:

dependency_overrides:
  http: any
  requests: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.7
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app.png"
flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/language/
    - assets/flag/

  fonts:
    - family: Regular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Italic
      fonts:
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
    - family: Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: BoldItalic
      fonts:
        - asset: fonts/Montserrat-BoldItalic.ttf
    - family: Extra
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf
    - family: ExtraItalic
      fonts:
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
    - family: Light
      fonts:
        - asset: fonts/Montserrat-Light.ttf
    - family: LightItalic
      fonts:
        - asset: fonts/Montserrat-LightItalic.ttf
    - family: Semibold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
    - family: SemiboldItalic
      fonts:
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
    - family: Thin
      fonts:
        - asset: fonts/Montserrat-Thin.ttf
    - family: ThinItalic
      fonts:
        - asset: fonts/Montserrat-ThinItalic.ttf
    - family: Black
      fonts:
        - asset: fonts/Montserrat-Black.ttf
    - family: BlackItalic
      fonts:
        - asset: fonts/Montserrat-BlackItalic.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
