

class ApiEndpoints {
  static const String baseUrl = 'https://hylana.wizz.app/api/v16';
  static const String login = '/login'; //@POST /email, password
  static const String reset = '/resetpassword';
  static const String overrideType="/overrides/commissions/types";
  static const String getAllUser="/all/users";
  static const String orgDetails="/organisations/details";
  static const String overrideWinnerDealer="/overrides/commissions/winners/dealers";
  static const String stockHistory="/stock-detail/history";
  static const String overrideReports="/overrides/reports";
  static const String getProductCoast="/assign-product-cost";
  static const String bonusWinner="/bonuses";
  static const String bonusWinnerDealer="/bonuses/dealers";
  static const String bonusRule="/bonus-rules";
  static const String bonusTypes="/bonus-types";
  static const String bonusOverlapping="/bonus-rules/overlapping";
  static const String allOverride="/overrides/commissions";
  static const String overrideUser="/override-users";
  static const String overrideUserDelete="/override-users-delete";
  static const String warehouses="/warehouses";
  static const String allAssignStock="/stock-pools/all-details";
  static const String deleteWarehouses="/delete-warehouse";
  static const String updateWarehouses="/update-warehouse";
  static const String postOverride="/overrides/commissions";
  static const String overrideWinner="/overrides/commissions/winners";
  static const String board="/boards";
  static const String getExpense="/users/expenses";
  static const String liveDemoList='/users/demos';
  static const String demoList='/users/demos';
  static const String postUnDemo="/users/demos/unsuccess-response";
  static const String postDemoNote="/users/demos/notes";
  static const String completeDemo ="/users/end-demo";
  static const String postLiveDemo="/users/start-demo";
  static const String expenseTypes="/users/expenses/types";
  static const String userdetails = '/userdetails';
  static const String stockPay = '/stock-pay';
  static const String postDistWarehouse = '/send-warehouses';
  static const String register = '/register';
  static const String sale = '/sales';
  static const String salesChangeStatus = '/sales/changestatus';
  static const String draw = '/draws'; //@GET -> @POST -> For Register
  static const String lead = '/leads'; //@GET -> @POST -> For Register
  static const String leadlist = '/leadlist'; //@GET -> @POST -> For Register
  static const String allleadlist = '/allleadlist'; //@GET -> @POST -> For Register
  static const String questions = '/questions'; //@GET -> @POST -> For Register
  static const String saleDetail = '/allsales/v2'; //@GET
  static const String dashboard = '/dashboard'; //@GET
  static const String competitions = '/competitions/'; //@GET
  static const String competitionsGallery = '/galery'; //@GET
  static const String distributors = '/distributors'; //@GET
  static const String users = '/users'; //@PUT
  static const String deviceregister = '/deviceregister'; //@POST
  static const String deviceremove = '/deviceremove'; //@POST
  static const String userupdate = '/userupdate'; //@PUT
  static const String resources = '/resources'; //@PUT
  static const String resourcesfav = '/resourcesfav'; //@PUT
  static const String newzipcode = '/newzipcode'; //@POST
  static const String location = '/location'; //@POST sale_id,longitude,latitude
  static const String material = '/material'; //@GET competitions.id
  static const String usergoals = '/usergoals'; //@GET competitions.id
  static const String marquee = '/marquee'; //@GET competitions.id
  static const String notifications = '/notifications'; //@GET competitions.id
  static const String assistboxusers = '/assistboxusers'; //@GET
  static const String leaderBoardDetail ='/leaderboard'; //@GET
  static const String mySales ='/user/careersales';//@POST MYSALES EKRANI
  static const String officeSales='/organisation/careersales';//@GET MYSALES EKRANI
  static const String postReferral ='/users/referral'; //POST
  static const String documenttypes = '/documenttypes'; //@GET
  static const String mydocuments = '/mydocuments'; //@GET
  static const String docadd = '/docadd'; //@POST
  static const String docupdate = '/docupdate'; //@POST
  static const String leadsReport="/reports/leads";
  static const String leadStatus="/lead-status";
  static const String myAppointment="/appointments";
  static const String allAppointment="/appointments?alldata=1";
  static const String postDemoQuestion="/users/demos/question-response";
  static const String assignSale="/users/demos/assign-sale";
  static const String stockReturnDist="/stocks/return-distributor";
  static const String edtAppointmentList="/getAppointmentSelectionData";
  static const String expenseSaleList="/users/sales";
  static const String postAppointment="/update-appointments";
  static const String reports="/dashboard/report";
  static const String getSocial="/users/socialmedia";
  static const String goalsDetails ="/usergoals";
  static const String reportDetails='/dashboard/report/v2';
  static const String assignStockBefore ="/assign-stock-before";
  static const String getDistributorContract ="/api/WizzEndpoints/contracts/distributors/{distributorId}";
  static const String distributorContractType ="/api/WizzEndpoints/contracts/{distributorId}";
  static const String postDistContract ="/api/WizzEndpoints/contracts/distributors";
  static const String postDistSignature ="/api/WizzEndpoints/signature/distributors";
  static const String assignDealar ="/stocks/assign-dealers";
  static const String salesDeduction="/sales/deductions";
  static const String postReceiveAmount ="/sales/reveice-amounts";
  static const String getDistSignature ="/api/WizzEndpoints/signatures/distributors/{distributorId}";

  //admin
  static const String comExist="/organisation/commissions/exists";
  static const String payPeriod="/pay-schedules";
  static const String allRoles ="/app/roles";
  static const String adminStockDealer ="/organisations/dealers";
  static const String allComReport="/commissions/recipients";
  static const String saleDetails="/allsales/v2";
  static const String adminStockList ="/organisations/stock-products";
  static const String adminPostStockDealer="/stocks/assign-dealers";
  static const String adminBase='https://apicustomerapp.wizz.app';
  static const String postExpense="/api/WizzEndpoints/users/expenses";
  static const String postSaleDocument="/api/WizzEndpoints/sales/documents";
  static const String saleDocument="/api/WizzEndpoints/sales/document-types";
  static const String getSaleDocument ="/api/WizzEndpoints/sales/{saleId}/documents";
  static const String adminCList='/api/admin/v1/Customers/reports';
  static const String adminSerialEnter='/api/admin/v1/Products/entered-serialnumbers';
  static const String adminRewardOrder='/api/admin/v1/Rewards/Orders';
  static const String adminReferralList='/api/admin/v1/Referrals';
  static const String adminCustomerEvent='/api/admin/v1/Customers/reward-events';
  static const String updateCustomerEvent='/api/admin/v1/Customers/approve-reward-events';
  static const String approveRewardOrder ='/api/admin/v1/Rewards/approve/orders/{transactionCode}';
  static const String cancelRewardOrder ='/api/admin/v1/Rewards/cancel/orders/{transactionCode}';
  static const String usedRewardOrder ='/api/admin/v1/Rewards/orders/{transactionCode}/used';
  static const String getSlider="/api/WizzEndpoints/silders";
  static const String postSlider="/api/WizzEndpoints/silders";
  static const String deleteSlider="/api/WizzEndpoints/silders";
  static const String adminContestList ="https://hylana.wizz.app/api/v16/getContest";
  static const String adminContract="/api/WizzEndpoints/contracts";
  static const String adminGetCommission="/organisation/commissions";
  static const String comReport ="/commissions/reports";
  static const String adminPostPay="/organisation/commissions/pay";
  static const String adminReturnPostPay="/organisation/commissions/refund-pay";
  static const String commissionTypes="/commissions/types";
  static const String commPostAmount="/organisation/commissions/amount-levels";
  static const String postComAdjust="/commissions/adjust";
  static const String commissionWinner="/commissions/recipients";
  static const String updateComRate="/organisation/commissions/amount-levels";
  static const String postCommission="/organisation/commissions";
  static const String checkCurrentAddCom="/organisation/commissions/amount-levels-overlapping";
  static const String comInactive="/organisation/commissions/in-active";
  static const String comActive="/organisation/commissions/active";
  static const String comExtendDate="/organisation/commissions/extend-date";
}
